version: "3"
services: 
    web:
      restart: always
      build: ./backend/
      container_name: one-inr-back
      image: one_inr:latest
      environment:
        - NODE_ENV=test
      links:
        - db:db
      ports:
        - "8901:9000"
      volumes:
        - /home/sonatan/new-one-inr/public/uploads/:/usr/src/app/public/uploads
        - /home/sonatan/new-one-inr/npmLogs/:/root/.npm/_logs

    db:
      build: ./mySql
      restart: always
      container_name: one_inr_db
      image: one_inr_db:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: one_inr_test
        MYSQL_PASSWORD: root
        MYSQL_USER: admin
      ports:
        - "3307:3306"
      volumes:
        - ./db_data:/var/lib/mysql    

    nginxApp:
      restart: always
      container_name:  one-inr-front
      image:  one-inr-front:latest
      build: ./frontend/
      environment:
        - ENV=development
      volumes:
        - ./logs/:/new-one-inr/logs
      ports:
        - '8906:80'
      links:
        - web:web

